components:
  examples:
    ErrorbroadcastOutOfRange:
      value:
        Code: broadcastOutOfRange
        Message: broadcast out of range
    ErrorgatewayOutOfRange:
      value:
        Code: gatewayOutOfRange
        Message: gateway out of range
    ErrorinvalidBroadcast:
      value:
        Code: invalidBroadcast
        Message: invalid broadcast
    ErrorinvalidGateway:
      value:
        Code: invalidGateway
        Message: invalid gateway
    ErrorinvalidRange:
      value:
        Code: invalidRange
        Message: invalid range
    ErrorinvalidReservedAddress:
      value:
        Code: invalidReservedAddress
        Message: invalid reserved address
    Erroripv4RangeNotFound:
      value:
        Code: ipv4RangeNotFound
        Message: ipv4Range not found
    ErrorrangeNameExists:
      value:
        Code: rangeNameExists
        Message: range name already exists
    ErrorreservedAddressCollideBroadcast:
      value:
        Code: reservedAddressCollideBroadcast
        Message: reserved address collide with broadcast
    ErrorreservedAddressCollideGateway:
      value:
        Code: reservedAddressCollideGateway
        Message: reserved address collide with gateway
    ErrorreservedAddressOutOfRange:
      value:
        Code: reservedAddressOutOfRange
        Message: reserved address out of range
  parameters:
    id:
      in: path
      name: id
      required: true
      schema:
        type: string
  responses:
    default:
      description: ""
  schemas:
    Error:
      format: error
      properties:
        code:
          type: string
        message:
          type: string
    Ipv4Range:
      properties:
        created:
          format: dateTime
          type: string
        gatewayIp:
          format: string
          type: string
        id:
          format: UUIDShort
          type: string
        name:
          format: string
          type: string
        rangeCidr:
          format: string
          type: string
        reservedIps:
          format: stringArray
          items:
            type: string
          type: array
        updated:
          format: dateTime
          type: string
      required:
      - id
      - name
      - rangeCidr
      - gatewayIp
      - reservedIps
      - created
      - updated
      type: object
    RequestPostIpv4Range:
      properties:
        gatewayIp:
          format: string
          type: string
        name:
          format: string
          type: string
        rangeCidr:
          format: string
          type: string
        reservedIPs:
          format: stringArray
          items:
            type: string
          type: array
      required:
      - name
      - rangeCidr
      - gatewayIp
      - reservedIPs
      type: object
    RequestPutIpv4Range:
      properties:
        gatewayIp:
          format: string
          type: string
        name:
          format: string
          type: string
        rangeCidr:
          format: string
          type: string
        reservedIps:
          format: stringArray
          items:
            type: string
          type: array
      required:
      - name
      - rangeCidr
      - gatewayIp
      - reservedIps
      type: object
    ResponseIpv4Range:
      properties:
        created:
          format: dateTime
          type: string
        gatewayIp:
          format: string
          type: string
        id:
          format: UUIDShort
          type: string
        name:
          format: string
          type: string
        rangeCidr:
          format: string
          type: string
        reservedIps:
          format: stringArray
          items:
            type: string
          type: array
        updated:
          format: dateTime
          type: string
      required:
      - id
      - name
      - rangeCidr
      - gatewayIp
      - reservedIps
      - created
      - updated
      type: object
    ResponseIpv4RangeList:
      properties:
        list:
          format: objectArray
          items:
            $ref: '#/components/schemas/Ipv4Range'
          type: array
      required:
      - list
      type: object
    ResponseSuccess:
      properties:
        Success:
          format: boolean
          type: boolean
      required:
      - Success
      type: object
info:
  contact:
    email: vyvoj@vshosting.cz
  description: OpenAPI 3.0.0 documentation for VSHosting s.r.o. project testinginterview.
  license:
    name: VSHosting s.r.o. client licence
    url: http://www.vshosting.cz
  title: testinginterview-public
  version: 3f8bfc847400e75c88a2e043930a49bd
openapi: 3.0.0
paths:
  /api/public/ipv4-range:
    get:
      description: Rozsahy
      operationId: 503daf9a-2d09-492e-801f-e26ef76b95a0
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseIpv4RangeList'
          description: Success response
      tags:
      - Ipv4Range
    post:
      description: Založení rozsahu
      operationId: 129417d3-9429-47f7-86bc-e857aa9fcb35
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestPostIpv4Range'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseIpv4Range'
          description: Success response
        "400":
          content:
            application/json:
              examples:
                gatewayOutOfRange:
                  $ref: '#/components/examples/ErrorgatewayOutOfRange'
                invalidBroadcast:
                  $ref: '#/components/examples/ErrorinvalidBroadcast'
                invalidGateway:
                  $ref: '#/components/examples/ErrorinvalidGateway'
                invalidRange:
                  $ref: '#/components/examples/ErrorinvalidRange'
                invalidReservedAddress:
                  $ref: '#/components/examples/ErrorinvalidReservedAddress'
                rangeNameExists:
                  $ref: '#/components/examples/ErrorrangeNameExists'
                reservedAddressCollideBroadcast:
                  $ref: '#/components/examples/ErrorreservedAddressCollideBroadcast'
                reservedAddressCollideGateway:
                  $ref: '#/components/examples/ErrorreservedAddressCollideGateway'
                reservedAddressOutOfRange:
                  $ref: '#/components/examples/ErrorreservedAddressOutOfRange'
              schema:
                $ref: '#/components/schemas/Error'
          description: Error response
      tags:
      - Ipv4Range
  /api/public/ipv4-range/{id}:
    delete:
      description: Smazání rozsahu
      operationId: acb706d9-f2be-440c-8eba-65ad6131e892
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseSuccess'
          description: Success response
        "400":
          content:
            application/json:
              examples:
                ipv4RangeNotFound:
                  $ref: '#/components/examples/Erroripv4RangeNotFound'
              schema:
                $ref: '#/components/schemas/Error'
          description: Error response
      tags:
      - Ipv4Range
    get:
      description: Rozsah
      operationId: 03d3992f-68a1-406e-87fc-d7fe60192be6
      parameters:
      - $ref: '#/components/parameters/id'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseIpv4Range'
          description: Success response
        "400":
          content:
            application/json:
              examples:
                ipv4RangeNotFound:
                  $ref: '#/components/examples/Erroripv4RangeNotFound'
              schema:
                $ref: '#/components/schemas/Error'
          description: Error response
      tags:
      - Ipv4Range
    put:
      description: Změna rozssahu
      operationId: 483462c0-4e10-4caa-977e-b8b44082d89a
      parameters:
      - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestPutIpv4Range'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseIpv4Range'
          description: Success response
        "400":
          content:
            application/json:
              examples:
                broadcastOutOfRange:
                  $ref: '#/components/examples/ErrorbroadcastOutOfRange'
                gatewayOutOfRange:
                  $ref: '#/components/examples/ErrorgatewayOutOfRange'
                invalidBroadcast:
                  $ref: '#/components/examples/ErrorinvalidBroadcast'
                invalidGateway:
                  $ref: '#/components/examples/ErrorinvalidGateway'
                invalidRange:
                  $ref: '#/components/examples/ErrorinvalidRange'
                invalidReservedAddress:
                  $ref: '#/components/examples/ErrorinvalidReservedAddress'
                ipv4RangeNotFound:
                  $ref: '#/components/examples/Erroripv4RangeNotFound'
                rangeNameExists:
                  $ref: '#/components/examples/ErrorrangeNameExists'
                reservedAddressCollideBroadcast:
                  $ref: '#/components/examples/ErrorreservedAddressCollideBroadcast'
                reservedAddressCollideGateway:
                  $ref: '#/components/examples/ErrorreservedAddressCollideGateway'
                reservedAddressOutOfRange:
                  $ref: '#/components/examples/ErrorreservedAddressOutOfRange'
              schema:
                $ref: '#/components/schemas/Error'
          description: Error response
      tags:
      - Ipv4Range
tags:
- name: Ipv4Range
